### ISSUE TITLE
broken import in `@geut/browser-node-core/url`

### ISSUE THREAD

**Issue by ph-fritsche** [geut/brode#2]
https://unpkg.com/browse/@geut/browser-node-core@2.0.1/src/url.js:
```js
import url from './esm/native-url.js'
```

This fails because https://unpkg.com/browse/@geut/browser-node-core@2.0.1/src/esm/native-url.js has no default export.

**Comment by tinchoz49** [comment]
Thank you for reporting the issue. Can you try the new version: 2.0.4 ?

**Comment by ph-fritsche** [comment]
Thanks for the quick fix. `url` shim seems to work now.
