### ISSUE TITLE
[zlib]: missing `module.createRequire` imported by `fflate`

### ISSUE THREAD

**Issue by ph-fritsche** [geut/brode#4]
https://unpkg.com/browse/@geut/browser-node-core@2.0.8/src/zlib.js:
```js
import { deflateSync, inflateSync, gzip, gunzip, zlibSync, unzlibSync } from 'fflate'
```

https://unpkg.com/browse/fflate@0.7.3/esm/index.mjs:
```js
import { createRequire } from 'module';
```

https://unpkg.com/browse/@geut/browser-node-core@2.0.8/src/module.js:
```js
export default {}
```

If `fflate` is installed, there is an error for missing `createRequire`.
If `fflate` is missing, there is an error for missing `deflateSync` etc..

**Comment by tinchoz49** [comment]
Thank you for check this. Now it should work :) v2.0.10
